import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import universities from "../../../data/universities.json";
import countries from "../../../data/countries.json";
import type { ApplicationDraft } from "../wizard/types";

const ALL_UNIS = [...universities.typeA, ...universities.typeB];
const uniName = (id?: string) => (id ? ALL_UNIS.find((u) => u.id === id)?.name ?? id : "");
const countryName = (code?: string) => (code ? countries.countries.find((c) => c.code === code)?.name ?? code : "");

function kv(label: string, value: string) {
  return new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true }),
      new TextRun({ text: value || "—" }),
    ],
  });
}

function h(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel] = HeadingLevel.HEADING_2) {
  return new Paragraph({ text, heading: level });
}

function multilineParagraphs(text: string): Paragraph[] {
  if (!text.trim()) return [new Paragraph({ children: [new TextRun({ text: "(empty)", italics: true })] })];
  return text.split(/\n{2,}/).map((block) =>
    new Paragraph({ children: [new TextRun(block.replace(/\n/g, " "))] }),
  );
}

export async function generateApplicationDocx(draft: ApplicationDraft): Promise<Uint8Array> {
  const p = draft.profile;
  const e = draft.education;
  const l = draft.languages;

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          h("Global Korea Scholarship 2026 — Application Draft", HeadingLevel.HEADING_1),
          kv("Track", draft.track ?? ""),
          kv("Generated", new Date().toLocaleDateString()),
          new Paragraph({ children: [new TextRun({ text: "Unofficial document generated by gks-for-u.", italics: true })] }),

          h("FORM 1 — Application", HeadingLevel.HEADING_1),
          h("Personal information"),
          kv("Family name", p.familyName ?? ""),
          kv("Given name", p.givenName ?? ""),
          kv("Middle name", p.middleName ?? ""),
          kv("Date of birth", p.dateOfBirth ?? ""),
          kv("Gender", p.gender ?? ""),
          kv("Citizenship", countryName(p.citizenshipCountryCode)),
          kv("Address country", p.addressCountry ?? ""),
          kv("Address line 1", p.addressLine1 ?? ""),
          kv("Address line 2", p.addressLine2 ?? ""),
          kv("Phone", p.phone ?? ""),
          kv("Email", p.email ?? ""),

          h("Education"),
          kv("High school", e.highSchoolName ?? ""),
          kv("Location", e.highSchoolCity ?? ""),
          kv("Attended", `${e.highSchoolStart ?? "?"} → ${e.highSchoolEnd ?? "?"}`),
          kv("Expected graduation", e.expectedGraduationDate ?? ""),
          kv("CGPA", e.gpaValue !== undefined ? `${e.gpaValue} / ${e.gpaScale}` : ""),

          h("Languages"),
          kv("TOPIK level", l.topikLevel === 0 ? "None" : `Level ${l.topikLevel}`),
          ...(l.englishTest && l.englishTest !== "none"
            ? [kv("English test", `${l.englishTest.toUpperCase()} ${l.englishScore ?? ""}`)]
            : []),

          h("University choices"),
          ...draft.universities.choices
            .map((c, i) =>
              c.universityId || c.department
                ? kv(`Choice ${i + 1}`, `${uniName(c.universityId)} — ${c.department ?? ""} (${c.fieldOfStudy ?? ""})`)
                : null,
            )
            .filter((x): x is Paragraph => x !== null),

          h("FORM 2 — Personal Statement", HeadingLevel.HEADING_1),
          ...multilineParagraphs(draft.essays.personalStatement),

          h("FORM 3 — Study Plan", HeadingLevel.HEADING_1),
          ...multilineParagraphs(draft.essays.studyPlan),

          h("FORM 4 — Recommendation Letter", HeadingLevel.HEADING_1),
          ...multilineParagraphs(draft.essays.recommendation),
          new Paragraph({ children: [new TextRun({ text: " " })] }),
          kv("Recommender signature", "________________________"),
          kv("Date", "________________________"),
        ],
      },
    ],
  });

  const buf = await Packer.toBuffer(doc);
  return new Uint8Array(buf);
}
