import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import universities from "../../../data/universities.json";
import countries from "../../../data/countries.json";
import type { ApplicationDraft } from "../wizard/types";

const ALL_UNIS = [...universities.typeA, ...universities.typeB];

function uniName(id?: string) {
  if (!id) return "";
  return ALL_UNIS.find((u) => u.id === id)?.name ?? id;
}

function countryName(code?: string) {
  if (!code) return "";
  return countries.countries.find((c) => c.code === code)?.name ?? code;
}

const UNICODE_MAP: Record<string, string> = {
  "→": "->", "←": "<-", "↔": "<->", "⇒": "=>", "⇐": "<=",
  "—": "-", "–": "-", "−": "-",
  "“": '"', "”": '"', "„": '"', "«": '"', "»": '"',
  "‘": "'", "’": "'", "‚": "'",
  "…": "...", "•": "*", "·": "*", "‧": "*",
  "©": "(c)", "®": "(R)", "™": "(TM)",
  "×": "x", "÷": "/", "±": "+/-",
  " ": " ", " ": " ", "​": "",
};

function sanitize(text: string): string {
  let out = "";
  for (const ch of text) {
    if (UNICODE_MAP[ch] !== undefined) {
      out += UNICODE_MAP[ch];
      continue;
    }
    const code = ch.charCodeAt(0);
    // WinAnsi-safe: printable ASCII + Latin-1 supplement (with a few gaps, but pdf-lib handles those)
    if (code <= 0xff) out += ch;
    else out += "?";
  }
  return out;
}

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 50;
const LINE_HEIGHT = 14;

class PdfWriter {
  doc: PDFDocument;
  font: PDFFont;
  bold: PDFFont;
  page!: PDFPage;
  y = PAGE_HEIGHT - MARGIN;

  constructor(doc: PDFDocument, font: PDFFont, bold: PDFFont) {
    this.doc = doc;
    this.font = font;
    this.bold = bold;
    this.newPage();
  }

  newPage() {
    this.page = this.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    this.y = PAGE_HEIGHT - MARGIN;
  }

  ensureSpace(needed: number) {
    if (this.y - needed < MARGIN) this.newPage();
  }

  h1(text: string) {
    this.ensureSpace(28);
    this.page.drawText(sanitize(text), { x: MARGIN, y: this.y - 18, size: 16, font: this.bold, color: rgb(0, 0, 0) });
    this.y -= 28;
  }

  h2(text: string) {
    this.ensureSpace(22);
    this.page.drawText(sanitize(text), { x: MARGIN, y: this.y - 14, size: 12, font: this.bold, color: rgb(0.1, 0.2, 0.5) });
    this.y -= 22;
  }

  kv(label: string, value: string) {
    this.ensureSpace(LINE_HEIGHT);
    this.page.drawText(sanitize(`${label}:`), { x: MARGIN, y: this.y - 10, size: 9, font: this.bold });
    this.page.drawText(sanitize(value || "-"), { x: MARGIN + 130, y: this.y - 10, size: 10, font: this.font });
    this.y -= LINE_HEIGHT;
  }

  paragraph(text: string) {
    if (!text) {
      this.kv("", "(empty)");
      return;
    }
    const maxWidth = PAGE_WIDTH - MARGIN * 2;
    const flush = (s: string) => {
      this.ensureSpace(LINE_HEIGHT);
      this.page.drawText(s, { x: MARGIN, y: this.y - 10, size: 10, font: this.font });
      this.y -= LINE_HEIGHT;
    };
    const lines = sanitize(text).replace(/\r/g, "").split(/\n/);
    for (let li = 0; li < lines.length; li++) {
      const tokens = lines[li].split(/(\s+)/);
      let line = "";
      for (const w of tokens) {
        const test = line + w;
        if (this.font.widthOfTextAtSize(test, 10) > maxWidth) {
          flush(line.trimEnd());
          line = w.trimStart();
        } else {
          line = test;
        }
      }
      if (line) flush(line);
      else if (li < lines.length - 1) this.y -= LINE_HEIGHT; // blank line between paragraphs
    }
    this.y -= 6;
  }

  spacer(n = 12) { this.y -= n; }
}

export async function generateApplicationPdf(draft: ApplicationDraft): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const w = new PdfWriter(doc, font, bold);

  // Cover
  w.h1("Global Korea Scholarship 2026 — Application Draft");
  w.kv("Track", draft.track ?? "");
  w.kv("Generated", new Date().toLocaleDateString());
  w.spacer();
  w.paragraph("Unofficial document generated by gks-for-u. Print, sign, and submit alongside the official forms from study.gks.go.kr. Verify every field against the official 2026 guideline before submission.");

  // FORM 1
  w.newPage();
  w.h1("FORM 1 — Application");

  w.h2("Personal information");
  const p = draft.profile;
  w.kv("Family name", p.familyName ?? "");
  w.kv("Given name", p.givenName ?? "");
  w.kv("Middle name", p.middleName ?? "");
  w.kv("Date of birth", p.dateOfBirth ?? "");
  w.kv("Gender", p.gender ?? "");
  w.kv("Citizenship", countryName(p.citizenshipCountryCode));
  w.kv("Address country", p.addressCountry ?? "");
  w.kv("Address line 1", p.addressLine1 ?? "");
  w.kv("Address line 2", p.addressLine2 ?? "");
  w.kv("Phone", p.phone ?? "");
  w.kv("Email", p.email ?? "");

  w.h2("Education");
  const e = draft.education;
  w.kv("High school", e.highSchoolName ?? "");
  w.kv("Location", e.highSchoolCity ?? "");
  w.kv("Attended", `${e.highSchoolStart ?? "?"} → ${e.highSchoolEnd ?? "?"}`);
  w.kv("Expected graduation", e.expectedGraduationDate ?? "");
  w.kv("CGPA", e.gpaValue !== undefined ? `${e.gpaValue} / ${e.gpaScale}` : "");
  if (e.classRankPercentile !== undefined) w.kv("Class rank percentile", `${e.classRankPercentile}%`);

  w.h2("Languages");
  const l = draft.languages;
  w.kv("TOPIK level", l.topikLevel === 0 ? "None" : `Level ${l.topikLevel}`);
  if (l.topikDate) w.kv("TOPIK date", l.topikDate);
  if (l.englishTest && l.englishTest !== "none") w.kv("English test", `${l.englishTest.toUpperCase()} ${l.englishScore ?? ""}`);

  w.h2("University choices");
  draft.universities.choices.forEach((c, i) => {
    if (!c.universityId && !c.department) return;
    w.kv(`Choice ${i + 1}`, `${uniName(c.universityId)} — ${c.department ?? ""} (${c.fieldOfStudy ?? ""})`);
  });

  // FORM 2
  w.newPage();
  w.h1("FORM 2 — Personal Statement");
  w.paragraph(draft.essays.personalStatement);

  // FORM 3
  w.newPage();
  w.h1("FORM 3 — Study Plan");
  const sp = draft.essays.studyPlan;
  const studyParts: Array<[string, string]> = [
    ["1. Language Study Plan", sp.languagePlan],
    ["2. Goal of Study & Study Plan", sp.goalOfStudy],
    ["3. Future Plan after Study", sp.futurePlan],
  ];
  let printedAny = false;
  for (const [heading, body] of studyParts) {
    if (!body?.trim()) continue;
    if (printedAny) w.spacer(12);
    w.h2(heading);
    w.paragraph(body);
    printedAny = true;
  }
  if (!printedAny) w.paragraph("");

  // FORM 4
  w.newPage();
  w.h1("FORM 4 — Recommendation Letter");
  w.paragraph(draft.essays.recommendation);
  w.spacer(40);
  w.kv("Recommender signature", "________________________");
  w.kv("Date", "________________________");

  return await doc.save();
}
